# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.66.0"
gem "rubocop-github", "~> 0.22.0"
gem "rubocop-minitest", "~> 0.35.1"
gem "rubocop-performance", "~> 1.21.0"
gem "rubocop-rails", "~> 2.25", ">= 2.25.0"
gem "rubocop-rake", "~> 0.7.0"
gem "rubocop-rspec", "~> 2.29.2"
gem "standard", "~> 1.41", ">= 1.41.0"
